services:
  backend:
    image: adnan23bcs35/2023bcs0035_backend:latest
    container_name: student-backend
    ports:
      - "8000:8000"
    environment:
      - PYTHONDONTWRITEBYTECODE=1
      - PYTHONUNBUFFERED=1
      - ALLOWED_ORIGINS=${ALLOWED_ORIGINS:-http://localhost:5173,http://127.0.0.1:5173,http://localhost,http://127.0.0.1}
    networks:
      - student-network
    restart: unless-stopped

  frontend:
    image: adnan23bcs35/2023bcs0035_frontend:latest
    container_name: student-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - student-network
    restart: unless-stopped

networks:
  student-network:
    driver: bridge
